import React from 'react';
import { TextLink } from '../sharedStyles'
import { SourcesWrapper, SourcesUl, SourceLi } from './styles'
export const DisplayResources = () => {
  return (
    <SourcesWrapper>
      <h1 className="display-3 mt-3">Resources</h1>
      <SourcesUl>
        <SourceLi>
          <TextLink
            href="https://medlineplus.gov/ency/article/003747.htm"
            target="_blank"
          >
            https://medlineplus.gov/ency/article/003747.htm
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.cdc.gov/coronavirus/2019-ncov/lab/guidelines-clinical-specimens.html"
            href="https://www.cdc.gov/coronavirus/2019-ncov/lab/guidelines-clinical-specimens.html"
            target="_blank"
          >
            https://www.cdc.gov/coronavirus/2019-ncov/lab/guidelines-clinical-specimens.html
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="http://www.hss.gov.yk.ca/pdf/npswab.pdf"
            href="http://www.hss.gov.yk.ca/pdf/npswab.pdf"
            target="_blank"
          >
            http://www.hss.gov.yk.ca/pdf/npswab.pdf
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="http://www.msdh.state.ms.us/msdhsite/index.cfm/14,8501,420,694,pdf/COVID-19_Specimen_Collection.pdf"
            href="http://www.msdh.state.ms.us/msdhsite/index.cfm/14,8501,420,694,pdf/COVID-19_Specimen_Collection.pdf"
            target="_blank"
          >
            http://www.msdh.state.ms.us/msdhsite/index.cfm/14,8501,420,694,pdf/COVID-19_Specimen_Collection.pdf
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.healthline.com/health/nasopharyngeal-culture#procedure"
            href="https://www.healthline.com/health/nasopharyngeal-culture#procedure"
            target="_blank"
          >
            https://www.healthline.com/health/nasopharyngeal-culture#procedure
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.cdc.gov/urdo/downloads/SpecCollectionGuidelines.pdf"
            href="https://www.cdc.gov/urdo/downloads/SpecCollectionGuidelines.pdf"
            target="_blank"
          >
            https://www.cdc.gov/urdo/downloads/SpecCollectionGuidelines.pdf
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/testing.html"
            href="https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/testing.html"
            target="_blank"
          >
            https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/testing.html
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.npr.org/sections/health-shots/2020/03/28/822869504/why-it-takes-so-long-to-get-most-covid-19-test-results"
            href="https://www.npr.org/sections/health-shots/2020/03/28/822869504/why-it-takes-so-long-to-get-most-covid-19-test-results"
            target="_blank"
          >
            https://www.npr.org/sections/health-shots/2020/03/28/822869504/why-it-takes-so-long-to-get-most-covid-19-test-results
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.fda.gov/medical-devices/emergency-situations-medical-devices/emergency-use-authorizations#covid19ivd"
            href="https://www.fda.gov/medical-devices/emergency-situations-medical-devices/emergency-use-authorizations#covid19ivd"
            target="_blank"
          >
            https://www.fda.gov/medical-devices/emergency-situations-medical-devices/emergency-use-authorizations#covid19ivd
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.verywellhealth.com/turbinates-types-purpose-and-disorders-1192107"
            href="https://www.verywellhealth.com/turbinates-types-purpose-and-disorders-1192107"
            target="_blank"
          >
            https://www.verywellhealth.com/turbinates-types-purpose-and-disorders-1192107
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.bloomberg.com/news/articles/2020-03-27/abbott-launches-5-minute-covid-19-test-for-use-almost-anywhere"
            href="https://www.bloomberg.com/news/articles/2020-03-27/abbott-launches-5-minute-covid-19-test-for-use-almost-anywhere"
            target="_blank"
          >
            https://www.bloomberg.com/news/articles/2020-03-27/abbott-launches-5-minute-covid-19-test-for-use-almost-anywhere
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.kff.org/uninsured/fact-sheet/what-issues-will-uninsured-people-face-with-testing-and-treatment-for-covid-19"
            href="https://www.kff.org/uninsured/fact-sheet/what-issues-will-uninsured-people-face-with-testing-and-treatment-for-covid-19"
            target="_blank"
          >
            https://www.kff.org/uninsured/fact-sheet/what-issues-will-uninsured-people-face-with-testing-and-treatment-for-covid-19
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.medicinenet.com/how_do_the_covid-19_coronavirus_tests_work/article.htm"
            href="https://www.medicinenet.com/how_do_the_covid-19_coronavirus_tests_work/article.htm"
            target="_blank"
          >
            https://www.medicinenet.com/how_do_the_covid-19_coronavirus_tests_work/article.htm
        </TextLink>
        </SourceLi>
        <SourceLi>
          <TextLink
            key="https://www.nbcnews.com/health/health-news/coronavirus-testing-information-covid-19-tests-according-state-health-departments-n1158041"
            href="https://www.nbcnews.com/health/health-news/coronavirus-testing-information-covid-19-tests-according-state-health-departments-n1158041"
            target="_blank"
          >
            https://www.nbcnews.com/health/health-news/coronavirus-testing-information-covid-19-tests-according-state-health-departments-n1158041
        </TextLink>
        </SourceLi>
      </SourcesUl>
    </SourcesWrapper>
  )
}
