
TARGET_DELETIONS_CSV_HEADER = [
    'PUBLIC_TEST_CENTER_ID'
]

TARGET_CSV_HEADER = [
    'NAME',
    'FULL_ADDRESS',
    'PHONE',
    'URL',
    'DESCRIPTION'
]

TARGET_PREPROCESSED_CSV_HEADER = [
    'EXTERNAL_ID',
    'NAME',
    'STREET_ADDRESS',
    'CITY',
    'STATE',
    'ZIP_CODE',
    'PHONE_NUMBER',
    'WEBSITE',
    'APPOINTMENT_REQUIRED',
    'DOCTOR_SCREEN_REQUIRED',
    'DRIVE_THRU_SITE',
    'PHYSICIAN_REFERRAL_REQUIRED',
    'VERIFIED_BY_EXTERNAL_PARTY',
    'DESCRIPTION',
    'HOURS_FREETEXT',
    'CUSTOM_QUESTION_1_STATUS'
]